### ISSUE TITLE
Keeps getting stuck on "Removing Cookie"

### ISSUE THREAD

**Issue by SummaryBob** [Baseult/LoLEsportsCapsuleFarmer#1]
Hey, so as the title says, whenever I start the bot, it keeps getting stuck on "Status: Removing Cookie".

In the debugger, it keeps repearing the lines like: (I replaced my username with [USER] to keep my account anonymous)

User: [USER] - Match: LEC - An error occurred while handling the cookie. - Timed out after 30 seconds
User: [USER] - Match: LEC - Rejecting cookie

Any ideas on what the issue could be?

**Comment by dreamswan** [comment]
remove any cookie disabler like adguard or any adblockers in chrome.

**Comment by SummaryBob** [comment]
> remove any cookie disabler like adguard or any adblockers in chrome.

Still doesnt work

**Comment by Baseult** [comment]
Enable "Use Javascript" in your settings. 
I'll fix that tomorrow.

**Comment by SummaryBob** [comment]
Sounds good, thanks!
