### ISSUE TITLE
Error: ChromeDriver version not found for Chrome version 115.0.5790

### ISSUE THREAD

**Issue by DimitriosMoliatsidis** [Baseult/LoLEsportsCapsuleFarmer#6]
Text From Debug 

{ As soon as you start the Bot you can read the Debugging Text here
Added user: wedrunkhim
Found 3 active streams
User: wedrunkhim - Match: LCK - Stream starting in new tab
User: wedrunkhim - Match: LCK - Stream cancelled. - Error: ChromeDriver version not found for Chrome version 115.0.5790
User: wedrunkhim - Match: VCS - Stream starting in new tab
User: wedrunkhim - Match: VCS - Stream cancelled. - Error: This instance has already started one or more requests. Properties can only be modified before sending the first request.
User: wedrunkhim - Match: Ultraliga - Stream starting in new tab
User: wedrunkhim - Match: Ultraliga - Stream cancelled. - Error: This instance has already started one or more requests. Properties can only be modified before sending the first request. }

updated local browser and it doesnt fix the issue . So is there something going on ?

**Comment by Baseult** [comment]
fixed
